version: '3.8'

services:
  web:
    build: ./django_celery
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./django_celery:/usr/src/app/
    ports:
      - 1337:8000
    env_file:
      - .env
    depends_on:
      - redis

  celery:
    build: ./django_celery
    command: celery -A django_celery worker --loglevel=info --logfile=logs/celery.log
    volumes:
      - ./django_celery:/usr/src/app/
      - ./django_celery:/usr/src/app/logs/
    env_file:
      - .env
    depends_on:
      - web
      - redis

  redis:
    image: redis:6-alpine

  dashboard:
    build: ./django_celery
    command: flower -A django_celery --port=5555 --broker=redis://redis:6379/0
    volumes:
      - ./django_celery:/usr/src/app/
    ports:
      - 5555:5555
    env_file:
      - .env
    depends_on:
      - web
      - redis
      - celery
